### ISSUE TITLE
Unexpected type required property

### ISSUE THREAD

**Issue by pimnijman** [ovenbits/ModelRocket#12]
_JSON_

```
{ "model": 15 } // This should be a string, but due to a server side bug, this is now an int.
```

_Swift_

``` swift
class Vehicle: Model {
    let model = Property<String>(key: "model", required: true)
}
```

_Expected behavior_
Since "model" is not of type String, but of type Int, I expect the the model property to become nil and since model is required I expect the vehicle object not to be initialized.

_Behaviour_
The vehicle object is initialized while the model property is nil.
This causes a crash when I unwrap the model property: `print("Vehicle make: \(vehicle.make.value!)")`

**Comment by jlandon** [comment]
Hey @pimnijman,

To fully utilize the required properties, you should use the `strictJSON:` initializer. See: https://github.com/ovenbits/ModelRocket#initializing-and-using-a-custom-object

The `json:` initializer does not account for required properties, so that initializer returns a non-optional model object, and the properties are not guaranteed to have non-nil values. What you're attempting to do works, if you use the `strictJSON:` initializer like this:

``` swift
if let vehicle = Vehicle(strictJSON: <json>) {
   print("Vehicle make: \(vehicle.make.value!)")
}
```
