### ISSUE TITLE
ModelRocket's performance

### ISSUE THREAD

**Issue by falcon4ever** [ovenbits/ModelRocket#20]
Hi,

I was wondering about ModelRocket's performance compared to a few other popular JSON mapper libraries:
https://github.com/bwhiteley/JSONShootout

However, due to the way of creating the class variables (e.g. let title = Property<Type>(key: "title"), I'm not sure how I can add ModelRocket to do a comparison. 

Looks like I will need to write an extension on these classes and member values:
- ModelObjects/Program.swift
- ModelObjects/Recording.swift

Any suggestions?

**Comment by jlandon** [comment]
Hey @falcon4ever,

Thanks for reaching out! JSONShootout uses value types (i.e. structs) for its models, but ModelRocket uses reference types (i.e. classes) which subclass the `Model` class. Because of that, you'll need to create new models for the ModelRocket tests. They could look something like this:

```swift
final class RecordingMR: Model, JSONTransformable {
    enum Status: String, JSONTransformable {
        case none      = "0"
        case recorded  = "-3"
        case recording = "-2"
        case unknown
    }
    
    enum RecGroup: String, JSONTransformable {
        case deleted = "Deleted"
        case default = "Default"
        case liveTV  = "LiveTV"
        case unknown
    }
    
    let startTsStr = Property<String>(key: "StartTs")
    let status     = Property<Status>(key: "Status")
    let recordId   = Property<String>(key: "RecordId")
    let recGroup   = Property<RecGroup>(key: "RecGroup")
}

final class ProgramMR: Model {
    let title     = Property<String>(key: "Title")
    let chanId    = Property<String>(key: "channel.ChanId")
    let desc      = Property<String>(key: "Description")
    let subtitle  = Property<String>(key: "SubTitle")
    let recording = Property<RecordingMR>(key: "Recording")
    let season    = Property<Int>(key: "Season")
    let episode   = Property<Int>(key: "Episode")
}
```

If you're simply curious how ModelRocket's performance compares, I ran it in JSONShootout's test suite, and here are the results:

|               Test               | Duration |
| --------------------- | --------- |
| `testDeserialization` |     0.08s   |
| `testPerformance`    |     0.55s   |

Let me know if you have any other questions. Thanks!

**Comment by falcon4ever** [comment]
Thanks @jlandon ! I'm mostly interested in ModelRocket's performance, while it has been performing fine for my needs, I just wasn't sure how it would compare to others.

I migrated from SwifyJSON as that one was underperforming and was trying to decide between Argo and the (back then new) ModelRocket. I'm surprised that the performance of Argo isn't as good as expected (since it's developed by a bigger team).
